name: build
on:
  pull_request:
  push:
  schedule:
    - cron: "0 0 1 * *"
jobs:
  Eval:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.1.0
      - name: Check environment
        run: |
          haxe --version
          haxelib version
      - name: Fetch sources
        uses: actions/checkout@v2
      - name: Install dependencies
        run: haxelib install all --always
      - name: Run tests
        run: haxe --interp test.hxml
  JavaScript:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.1.0
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Check environment
        run: |
          node --version
          npm --version
      - name: Fetch sources
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          haxelib install hxnodejs
          haxelib install all --always
          npm install --ignore-scripts
      - name: Run tests
        run: |
          haxe --define js-es=6 --js var/tests.js --library hxnodejs test.hxml
          node var/tests.js
  NekoVM:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.1.0
      - name: Check environment
        run: neko -version
      - name: Fetch sources
        uses: actions/checkout@v2
      - name: Install dependencies
        run: haxelib install all --always
      - name: Run tests
        run: |
          haxe --neko var/tests.n test.hxml
          neko var/tests.n
  PHP:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.1.0
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          extensions: mbstring
      - name: Check environment
        run: |
          php --version
          composer --version
      - name: Fetch sources
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          haxelib install all --always
          composer install --no-interaction
      - name: Run tests
        run: |
          haxe --define php-lib=php --php lib test.hxml
          php lib/index.php
